language: php

sudo: required

addons:
  hosts:
    - simplesamlphp.test
  firefox: "47.0.1"
  postgresql: "9.4"
  apt:
    packages:
      - oracle-java9-installer
      - oracle-java9-set-default
      - redis-server

services:
  - redis-server

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

# Alternate tests with MySQL and PostgreSQL
matrix:
  include:
    - php: 7.0
      env: DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli  MOODLE_BRANCH=master
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master

before_install:
  - phpenv config-rm xdebug.ini
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - bash tests/idp/simplesamlphp.sh
  - cd ../..
  - nvm install 8.9
  - nvm use 8.9
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv
  - echo '$CFG->cookiesecure = false;' >> moodle/config.php
  - moodle-plugin-ci add-config 'define("AUTH_SAML2_REDIS_STORE_TEST_SERVER", "127.0.0.1");'
  - moodle-plugin-ci add-config 'define("AUTH_SAML2_TEST_IDP_METADATA", "http://simplesamlphp.test:8001/saml2/idp/metadata.php");'

script:
  # Run lint on extlib as composer may fetch newer PHP version of libs during update.
  - find moodle/auth/saml2/extlib -type f -name '*.php' -exec php -l {} \; | (! grep -v "No syntax errors detected" )
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  #- moodle-plugin-ci phpdoc
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat